# Generated by Django 2.1 on 2018-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0002_auto_20181010_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderschema',
            name='order_id',
            field=models.IntegerField(default=85216),
        ),
    ]
