# Generated by Django 2.1 on 2018-10-10 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0004_auto_20181010_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
